ynfinite-contao-com-load:
  path: /ynfinite/com/lead/
  defaults:
    _controller: "YnfiniteContaoComBundle:Lead:index"

ynfinite-contao-com-send:
  path: /ynfinite/com/lead/send
  defaults:
    _controller: "YnfiniteContaoComBundle:Lead:send"