services:
  ynfinite.contao-com.listener.communication:
    class: 'Ynfinite\ContaoComBundle\EventListener\YnfiniteCommunicationService'
    arguments:
      - "@contao.framework"

  ynfinite.contao-com.email:
    class: 'Ynfinite\ContaoComBundle\EventListener\YnfiniteEmailService'
    arguments:
      - "@contao.framework"
      - "@mailer"
      - "@templating"

  ynfinite.contao-com.formgenerator:
    class: 'Ynfinite\ContaoComBundle\EventListener\YnfiniteFormGeneratorService'
    arguments:
      - "@contao.framework"